version: "3"
services:
    bitcoin_lnbits:
        image: lnbits
        restart: unless-stopped
        stop_signal: SIGKILL
        environment:
          LNBITS_BACKEND_WALLET_CLASS: LndWallet
          LND_GRPC_ENDPOINT: lnd_bitcoin
          LND_GRPC_PORT: 10009
          LND_GRPC_CERT: "/etc/lnd/tls.cert"
          LND_GRPC_MACAROON: "/etc/lnd/admin.macaroon"
          LNBITS_DATA_FOLDER: "/app/data"
        volumes:
            - "lnd_bitcoin_datadir:/etc/lnd"
            - "lnd_bitcoin_lnbits_datadir:/app/data"
        expose:
            - "3000"
        # command: ["npm", "run", "start:cookie", "--", "/data/.cookie"]
        links:
            - lnd_bitcoin
volumes:
    lnd_bitcoin_lnbits_datadir:
required:
    - "bitcoin-lnd"
